### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'oft WDT reset'

### ISSUE THREAD

**Issue by Andrew-fedoralabs** [mrjimenez/JTAG#1]
Hello,
I am trying to run the python loader and keep getting the following issue. Im not sure what is causing the problem. Thanks in advance for the help!

python xsvf test1.xsvf 
Unrecognized line: r...l..r...#..n............p.<.....8.........p....nn...;.n........b.$.r..r..p.n..........l.........b..n..n.$......b...~.n.......l`.....#.n...r....nr...;....?...;...r...n....b...`....l..........r....n.b..
File: /home/ubuntu1604/Arduino/libraries/JTAG/extras/python/test1.xsvf
Ready to send 506578 bytes.
Sent:      255 bytes,   506323 remaining
Traceback (most recent call last):
  File "xsvf", line 57, in <module>
    main()
  File "xsvf", line 46, in main
    u.upload_all_files(args.fileName)
  File "/home/ubuntu1604/Arduino/libraries/JTAG/extras/python/Uploader.py", line 148, in upload_all_files
    ok = self.upload_one_file(fd)
  File "/home/ubuntu1604/Arduino/libraries/JTAG/extras/python/Uploader.py", line 103, in upload_one_file
    num_bytes = int(argument)
ValueError: invalid literal for int() with base 10: 'oft WDT reset'

**Comment by mrjimenez** [comment]
Hi Andrew,

What is the content of the file /home/ubuntu1604/Arduino/libraries/JTAG/extras/python/test1.xsvf? Please, post the output of the command "hexdump -C /home/ubuntu1604/Arduino/libraries/JTAG/extras/python/test1.xsvf".

**Comment by Andrew-fedoralabs** [comment]
attached is the hex dump. Thanks!
[hexdump.txt](https://github.com/mrjimenez/JTAG/files/1123202/hexdump.txt)

**Comment by mrjimenez** [comment]
Are you using an ESP? The line "ValueError: invalid literal for int() with base 10: 'oft WDT reset'" implies that the board is resetting due to watchdog timeout. If that is the case, I can take a look at this issue tomorrow.

**Comment by Andrew-fedoralabs** [comment]
Yes I am using an ESP8266. That would be much appreciated!

**Comment by mrjimenez** [comment]
Hi Andrew,

I wrote a small fix, but I don't have the proper hardware to test it. Would you mind testing it for me?

I have created a branch called "espfix1" that you can pull or clone.

Best regards,
Marcelo.

**Comment by Andrew-fedoralabs** [comment]
Hello Marcelo,

Thank you for the quick reply! I will test it and let you know the results.


Andrew Archer

**Comment by Andrew-fedoralabs** [comment]
Hey Marcelo,

Thanks again for all this help!
I am getting compile errors ( see below). I am using http://arduino.esp8266.com/stable/package_esp8266com_index.json for the board packages and compiling with the sparkfun ESP8266 Thing Dev board selection. I have found the generic ESP8266 board misses things that are needed and will compile without errors in certain cases.
arduino v1.8.3

The first error I get is the following. To fix it I changed all of the uint8_t to uint32_t. Not the best fix but it did work.

> /home/ubuntu1604/Arduino/libraries/JTAG/src/ArduinoPin.cpp: In constructor 'ArduinoInputPin::ArduinoInputPin(uint8_t)':
> /home/ubuntu1604/Arduino/libraries/JTAG/src/ArduinoPin.cpp:18:33: error: cannot convert 'volatile uint32_t* {aka volatile unsigned int*}' to 'volatile uint8_t* {aka volatile unsigned char*}' in initialization
>  , m_in(portInputRegister(port()))
>                                  ^
> /home/ubuntu1604/Arduino/libraries/JTAG/src/ArduinoPin.cpp: In constructor 'ArduinoOutputPin::ArduinoOutputPin(uint8_t)':
> /home/ubuntu1604/Arduino/libraries/JTAG/src/ArduinoPin.cpp:24:35: error: cannot convert 'volatile uint32_t* {aka volatile unsigned int*}' to 'volatile uint8_t* {aka volatile unsigned char*}' in initialization
>  , m_out(portOutputRegister(port()))

This is the last error I am getting, not sure what needs to be fixed here.

> In file included from /home/ubuntu1604/Arduino/JTAGTest/JTAGTest.ino:4:0:
> /home/ubuntu1604/Arduino/libraries/JTAG/src/PlayXSVFJTAGArduino.h:20:17: error: cannot declare field 'PlayXSVFJTAGArduino::m_xsvf_player' to be of abstract type 'XSVFPlayerJTAG'
>   XSVFPlayerJTAG m_xsvf_player;
>                  ^
> In file included from /home/ubuntu1604/Arduino/libraries/JTAG/src/PlayXSVFJTAGArduino.h:9:0,
>                  from /home/ubuntu1604/Arduino/JTAGTest/JTAGTest.ino:4:
> /home/ubuntu1604/Arduino/libraries/JTAG/src/XSVFPlayerJTAG.h:9:7: note:   because the following virtual functions are pure within 'XSVFPlayerJTAG':
>  class XSVFPlayerJTAG : public XSVFPlayer
>        
> 
> 
> In file included from /home/ubuntu1604/Arduino/libraries/JTAG/src/XSVFPlayerJTAG.h:7:0,
>                  from /home/ubuntu1604/Arduino/libraries/JTAG/src/PlayXSVFJTAGArduino.h:9,
>                  from /home/ubuntu1604/Arduino/JTAGTest/JTAGTest.ino:4:
> /home/ubuntu1604/Arduino/libraries/JTAG/src/XSVFPlayer.h:284:15: note: 	virtual void XSVFPlayer::execute_XCOMMENT_auxiliar(uint32_t)
>   virtual void execute_XCOMMENT_auxiliar(uint32_t c) = 0;

**Comment by mrjimenez** [comment]
Hi Andrew,

I have adapted the library to compile in esp8266 architecture without errors, but since right now I don't have the hardware to test, would you please test it and report back?

The changes are now on master. If you tell me all is ok, I'll do a new release.

Best regards,
Marcelo.

**Comment by Andrew-fedoralabs** [comment]
Hello Marcelo,

Sorry for the long reply, I have been out for personal reasons. I am getting back to working on this and have time to dedicate to fixing it. I have opened and tried to compile and am getting these errors:

WARNING: library JTAG claims to run on (avr) architecture(s) and may be incompatible with your current board which runs on (esp8266) architecture(s).
Generating function prototypes...
"/home/ubuntu1604/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/ubuntu1604/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-I/home/ubuntu1604/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-I/tmp/arduino_build_458648/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L -DLWIP_OPEN_SRC   -DARDUINO=10803 -DARDUINO_ESP8266_THING_DEV -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_THING_DEV"  -DESP8266 "-I/home/ubuntu1604/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266" "-I/home/ubuntu1604/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/variants/thing" "-I/home/ubuntu1604/Arduino/libraries/JTAG/src" "/tmp/arduino_build_458648/sketch/JTAGTest.ino.cpp" -o "/tmp/arduino_build_458648/preproc/ctags_target_for_gcc_minus_e.cpp"
"/opt/arduino-1.8.3/tools-builder/ctags/5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "/tmp/arduino_build_458648/preproc/ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
"/home/ubuntu1604/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/ubuntu1604/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-I/home/ubuntu1604/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-I/tmp/arduino_build_458648/core" -c -Wall -Wextra -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC   -DARDUINO=10803 -DARDUINO_ESP8266_THING_DEV -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_THING_DEV"  -DESP8266 "-I/home/ubuntu1604/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266" "-I/home/ubuntu1604/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/variants/thing" "-I/home/ubuntu1604/Arduino/libraries/JTAG/src" "/tmp/arduino_build_458648/sketch/JTAGTest.ino.cpp" -o "/tmp/arduino_build_458648/sketch/JTAGTest.ino.cpp.o"
Compiling libraries...
Compiling library "JTAG"
"/home/ubuntu1604/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/ubuntu1604/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-I/home/ubuntu1604/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-I/tmp/arduino_build_458648/core" -c -Wall -Wextra -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC   -DARDUINO=10803 -DARDUINO_ESP8266_THING_DEV -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_THING_DEV"  -DESP8266 "-I/home/ubuntu1604/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266" "-I/home/ubuntu1604/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/variants/thing" "-I/home/ubuntu1604/Arduino/libraries/JTAG/src" "/home/ubuntu1604/Arduino/libraries/JTAG/src/ArduinoPin.cpp" -o "/tmp/arduino_build_458648/libraries/JTAG/ArduinoPin.cpp.o"
/home/ubuntu1604/Arduino/libraries/JTAG/src/ArduinoPin.cpp: In constructor 'ArduinoInputPin::ArduinoInputPin(uint8_t)':
/home/ubuntu1604/Arduino/libraries/JTAG/src/ArduinoPin.cpp:18:33: error: cannot convert 'volatile uint32_t* {aka volatile unsigned int*}' to 'volatile uint8_t* {aka volatile unsigned char*}' in initialization
 , m_in(portInputRegister(port()))
                                 ^
/home/ubuntu1604/Arduino/libraries/JTAG/src/ArduinoPin.cpp: In constructor 'ArduinoOutputPin::ArduinoOutputPin(uint8_t)':
/home/ubuntu1604/Arduino/libraries/JTAG/src/ArduinoPin.cpp:24:35: error: cannot convert 'volatile uint32_t* {aka volatile unsigned int*}' to 'volatile uint8_t* {aka volatile unsigned char*}' in initialization
 , m_out(portOutputRegister(port()))
                                   ^
Using library JTAG at version 1.0.14 in folder: /home/ubuntu1604/Arduino/libraries/JTAG 
exit status 1
Error compiling for board SparkFun ESP8266 Thing Dev.

Thanks!

**Comment by mrjimenez** [comment]
Hi, Andrew,

Please test with release 1.0.15, this error should have been corrected.

I will reopen the issue, so that you can close it if that is the case.

Regards,
Marcelo.

**Comment by Andrew-fedoralabs** [comment]
Hello Marcelo,

I was able to test, compile and upload the sketch to the ESP32. I then proceeded to run the python program to upload the xsvf file. I changed the uploader to the correct port and ran. I received the following error repeating:

File: /home/ubuntu1604/JTAG-1.0.15/extras/xsvf/test1.xsvf
Ready to send 506578 bytes.
Unrecognized line: Guru Meditation Error of type LoadProhibited occurred on core  1. Exception was unhandled.
File: /home/ubuntu1604/JTAG-1.0.15/extras/xsvf/test1.xsvf
Ready to send 506578 bytes.
Unrecognized line: PC      : 0x400811bd  PS      : 0x00060530  A0      : 0x800d0b3a  A1      : 0x3ffcea50
Unrecognized line: A2      : 0x00000009  A3      : 0x00000002  A4      : 0x0000001f  A5      : 0x00000000
Unrecognized line: A6      : 0x00000000  A7      : 0x00000000  A8      : 0x3f401bcc  A9      : 0xaaaaaaaa
Unrecognized line: A10     : 0xaaaaaaaa  A11     : 0x00000054  A12     : 0x00000003  A13     : 0x0000ff00
Unrecognized line: A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x00000017  EXCCAUSE: 0x0000001c
Unrecognized line: EXCVADDR: 0xaaaaaaaa  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xfffffffe
Unrecognized line: Backtrace: 0x400811bd:0x3ffcea50 0x400d0b37:0x3ffcea70 0x400d0b68:0x3ffcea90 0x400d0bb0:0x3ffceab0 0x400d0e8d:0x3ffceae0 0x400d0abe:0x3ffceb20 0x400de799:0x3ffcef90
File: /home/ubuntu1604/JTAG-1.0.15/extras/xsvf/test1.xsvf
Ready to send 506578 bytes.
Unrecognized line: ets Jun  8 2016 00:22:57
Unrecognized line: rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
Unrecognized line: configsip: 0, SPIWP:0xee
Unrecognized line: clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
Unrecognized line: mode:DIO, clock div:1
Unrecognized line: load:0x3fff0010,len:4
Unrecognized line: load:0x3fff0014,len:572
Unrecognized line: load:0x40078000,len:0
Unrecognized line: load:0x40078000,len:9880
Unrecognized line: entry 0x400789d8

Thanks!

**Comment by Andrew-fedoralabs** [comment]
After more debugging. I found an issue using one of the pins I had configured. I switched the pin and now am getting this:

!*****************************
!Failure at instruction #    1
!*****************************
!Last TDO: /0 bits
!Processed 1 instructions.
!Checksum:  0x00/0.
!Sum: 0x00000000/0.

Q-100,XCOMPLETE not reached

RXSVF

S63  

Q-10,VREF is not present. Please, check the cable.

I have tried pulling VREF high and low and it is having no effect. Its currently on pin 27. I'm using the ESP32 thing from sparkfun for reference.
