### ISSUE TITLE
Error in Uploader.py

### ISSUE THREAD

**Issue by r1ccard0** [mrjimenez/JTAG#7]
When I use it under Win 10 x64 (with both x86 and x64 Python 3.9.2 and 3.8.6), I get:

c:\Users\Riccardo\Documenti\Arduino\libraries\JTAG\extras\python>python xsvf -p COM4 D:\output.xsvf
Traceback (most recent call last):
  File "xsvf", line 8, in <module>
    import Uploader
  File "c:\Users\Riccardo\Documenti\Arduino\libraries\JTAG\extras\python\Uploader.py", line 16, in <module>
    class Uploader(object):
  File "c:\Users\Riccardo\Documenti\Arduino\libraries\JTAG\extras\python\Uploader.py", line 23, in Uploader
    [(chr(x) in _printable_chars) and chr(x) or '.' for x in range(256)])
  File "c:\Users\Riccardo\Documenti\Arduino\libraries\JTAG\extras\python\Uploader.py", line 23, in <listcomp>
    [(chr(x) in _printable_chars) and chr(x) or '.' for x in range(256)])
NameError: name '_printable_chars' is not defined

How can I fix? Is it there anything wrong with my files paths?

**Comment by mrjimenez** [comment]
Hi Riccardo,

The program is a little old and was originally done in Python2, so that is likely a problem of Python compatibility.

You can try to substitute `_printable_chars` by `string.printable` everywhere in the code, but you are likely to find other problems.

If possible, try to run with a python 2 interpreter.

**Comment by r1ccard0** [comment]
Hi Marcelo,

thank You for your reply.

I tried to edit the source files by deleting the latest modification and it
worked like a charm.

I used python 2 under mac OS.

Regards,

Riccardo

Il giorno sab 27 mar 2021 alle ore 19:26 Marcelo Roberto Jimenez <
***@***.***> ha scritto:
